# Generated by Django 3.2.8 on 2021-10-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_subjects',
            name='modified_on',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
