# Generated by Django 3.2.8 on 2021-10-21 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_subjects_modified_on'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student_subjects',
            unique_together={('student', 'subject')},
        ),
    ]
