# Generated by Django 3.2.8 on 2021-10-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('book_url', models.URLField()),
                ('students_opted', models.IntegerField(default=0)),
                ('updated_on', models.DateTimeField(default=None)),
            ],
        ),
    ]
