# Generated by Django 3.2.8 on 2021-10-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
