# Generated by Django 3.2.8 on 2021-10-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_alter_subject_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='updated_on',
            field=models.DateTimeField(null=True),
        ),
    ]
