# Generated by Django 3.2.8 on 2021-10-26 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_alter_subject_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='students_opted',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
